version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: misinfodetector-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: misinfodetector
    volumes:
      - mongodb_data:/data/db
    networks:
      - misinfodetector-network

  redis:
    image: redis:7-alpine
    container_name: misinfodetector-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - misinfodetector-network

  backend:
    build: ./backend
    container_name: misinfodetector-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://admin:password@mongodb:27017/misinfodetector?authSource=admin
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your_super_secret_jwt_key_change_this_in_production
      FRONTEND_URL: http://localhost:3000
    depends_on:
      - mongodb
      - redis
    volumes:
      - backend_uploads:/app/uploads
    networks:
      - misinfodetector-network

  frontend:
    build: ./frontend
    container_name: misinfodetector-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      REACT_APP_API_URL: http://localhost:5000/api
    depends_on:
      - backend
    networks:
      - misinfodetector-network

volumes:
  mongodb_data:
  redis_data:
  backend_uploads:

networks:
  misinfodetector-network:
    driver: bridge
